"use client";
import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Droplet, Heart, HeartHandshake, Info, Loader2, LockKeyhole, LogOut, MapPin, Phone, Search, ShieldCheck, SlidersHorizontal, UserRound, Users, X } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Checkbox } from "@/components/ui/checkbox";
import { Empty } from "@/components/ui/empty";
import { Pagination } from "@/components/ui/pagination";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Toaster, toast } from "sonner";
import { BLOOD_GROUPS, profileSchema, type Donor, type ProfileInput, type SearchResult, type Session } from "@/lib/contracts";

const samples: Donor[] = [
 { id:"example-1",name:"Aarav S.",bloodGroup:"O+",city:"Thane",area:"Kopri",available:true,updatedAt:0,sample:true },
 { id:"example-2",name:"Meera P.",bloodGroup:"B+",city:"Kalyan",area:"Kalyan West",available:true,updatedAt:0,sample:true },
 { id:"example-3",name:"Rohan K.",bloodGroup:"A+",city:"Navi Mumbai",area:"Vashi",available:true,updatedAt:0,sample:true },
 { id:"example-4",name:"Isha D.",bloodGroup:"AB-",city:"Mumbai",area:"Dadar",available:false,updatedAt:0,sample:true }
];
const emptyResult:SearchResult = {donors:[],total:0,page:1,pages:1,stats:{registered:0,available:0,cities:0}};
type Filters = {group:string;city:string;available:boolean;page:number};
const initialFilters:Filters={group:"all",city:"",available:true,page:1};
function GroupSelect({value,onChange,id,all=false}:{value:string;onChange:(v:string)=>void;id:string;all?:boolean}) {
 return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="field-select"><SelectValue placeholder="Select blood group"/></SelectTrigger><SelectContent position="popper">{all&&<SelectItem value="all">All blood groups</SelectItem>}{BLOOD_GROUPS.map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select>;
}
export default function BloodBridge() {
 const [view,setView]=useState("find");
 const [session,setSession]=useState<Session|null>(null),[sessionError,setSessionError]=useState("");
 const [filters,setFilters]=useState<Filters>(initialFilters),[draftGroup,setDraftGroup]=useState("all"),[draftCity,setDraftCity]=useState("");
 const [result,setResult]=useState<SearchResult>(emptyResult),[loading,setLoading]=useState(true),[searchError,setSearchError]=useState("");
 const [examples,setExamples]=useState(false),[refresh,setRefresh]=useState(0);
 const [registerOpen,setRegisterOpen]=useState(false),[authOpen,setAuthOpen]=useState(false);
 const [contactDonor,setContactDonor]=useState<Donor|null>(null),[contactPhone,setContactPhone]=useState(""),[contactError,setContactError]=useState("");
 const [deleteOpen,setDeleteOpen]=useState(false),[busy,setBusy]=useState(false);
 const sessionRef=useRef(session);sessionRef.current=session;
 async function api(path:string,options:RequestInit={}) {
  const res=await fetch(path,{...options,credentials:"same-origin",headers:{"Content-Type":"application/json","X-BloodBridge-Request":"1",...(sessionRef.current?.csrf?{"X-CSRF-TOKEN":sessionRef.current.csrf}:{}),...options.headers}});
  let data;try{data=await res.json();}catch{throw new Error("The service is temporarily unavailable. Please try again.");}
  if(!res.ok)throw new Error(data.error||"Something went wrong. Please try again.");return data;
 }
 async function loadSession(){try{const s=await api("/api/session");setSession(s);sessionRef.current=s;setSessionError("");return s as Session;}catch(err){setSessionError((err as Error).message);return null;}}
 useEffect(()=>{void loadSession();const route=()=>{const v=location.hash.replace("#","");setView(v==="profile"||v==="about"?v:"find");};route();window.addEventListener("hashchange",route);return()=>window.removeEventListener("hashchange",route);},[]);
 useEffect(()=>{if(examples)return;const controller=new AbortController();setLoading(true);setSearchError("");const q=new URLSearchParams({group:filters.group,city:filters.city,available:String(filters.available),page:String(filters.page)});api(`/api/donors?${q}`,{signal:controller.signal}).then(setResult).catch(err=>{if(err.name!=="AbortError")setSearchError(err.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[filters,refresh,examples]);
 useEffect(()=>{if(!contactDonor||contactDonor.sample||!session?.user)return;let cancelled=false;setContactPhone("");setContactError("");api(`/api/donors/${contactDonor.id}/contact`).then(d=>{if(!cancelled)setContactPhone(d.phone);}).catch(err=>{if(!cancelled)setContactError(err.message);});return()=>{cancelled=true;};},[contactDonor,session?.user?.id]);
 function navigate(v:string){location.hash=v;setView(v);window.scrollTo({top:0,behavior:"smooth"});}
 function register(){if(!session){toast.error(sessionError||"Your account is loading. Please try again in a moment.");return;}if(!session.user){setAuthOpen(true);return;}setRegisterOpen(true);}
 async function saveProfile(values:ProfileInput){await api("/api/profile",{method:"PUT",body:JSON.stringify(values)});await loadSession();setRefresh(v=>v+1);setRegisterOpen(false);setExamples(false);toast.success("Your donor profile has been saved.");navigate("profile");}
 async function toggleAvailability(available:boolean){if(!session?.profile||busy)return;setBusy(true);try{await api("/api/profile/availability",{method:"PATCH",body:JSON.stringify({available})});await loadSession();setRefresh(v=>v+1);toast.success(available?"You are now listed as available.":"Your availability is paused.");}catch(err){toast.error((err as Error).message);}finally{setBusy(false);}}
 async function deleteProfile(){setBusy(true);try{await api("/api/profile",{method:"DELETE"});await loadSession();setRefresh(v=>v+1);setDeleteOpen(false);toast.success("Your donor profile and contact details have been deleted.");}catch(err){toast.error((err as Error).message);}finally{setBusy(false);}}
 async function signOut(){if(session?.mode==="platform"){window.location.assign(session.signOutUrl||"/signout-with-chatgpt?return_to=/");return;}try{await api("/api/auth/logout",{method:"POST"});await loadSession();navigate("find");toast.success("You have signed out.");}catch(err){toast.error((err as Error).message);}}
 function resetFilters(){setDraftGroup("all");setDraftCity("");setFilters(initialFilters);}
 const displayed=examples?samples.filter(d=>(filters.group==="all"||d.bloodGroup===filters.group)&&(!filters.city||`${d.city} ${d.area}`.toLowerCase().includes(filters.city.toLowerCase()))&&(!filters.available||d.available)):result.donors;
 const count=examples?displayed.length:result.total,activeFilters=filters.group!=="all"||!!filters.city;
 return <div className="app-shell"><Toaster position="bottom-right" richColors closeButton/>
 <header className="site-header"><div className="header-inner"><a className="brand" href="#find" onClick={()=>navigate("find")} aria-label="BloodBridge home"><span className="brand-symbol"><Droplet fill="currentColor" strokeWidth={1.4}/></span><span>Blood<span className="brand-accent">Bridge</span><small>EVERY CONNECTION COUNTS</small></span></a><nav aria-label="Main navigation"><a className={view==="find"?"active":""} href="#find">Find donors</a><a className={view==="about"?"active":""} href="#about">How it works</a><a className={view==="profile"?"active":""} href="#profile">My profile</a></nav><div className="header-actions">{session?.user?<button className="account-button" onClick={()=>navigate("profile")} aria-label="Open your profile"><UserRound size={18}/><span>{session.user.name.split(" ")[0].split("@")[0]}</span></button>:<button className="text-button sign-in-button" onClick={()=>setAuthOpen(true)}>Sign in</button>}<button className="btn primary header-register" onClick={register}><Heart size={16}/>Become a donor</button></div></div></header>
 {view==="find"&&<main className="main-wrap"><section className="intro-row"><div><div className="eyebrow"><span className="eyebrow-line"/>A COMMUNITY THAT SHOWS UP</div><h1>Find a donor.<br/><span>Make a connection.</span></h1><p>Someone nearby could be the help you’re looking for.</p></div><div className="intro-note"><ShieldCheck size={22}/><p>Voluntary donors.<br/><strong>Protected contact details.</strong></p></div></section>
 <form className="search-panel" onSubmit={e=>{e.preventDefault();setFilters({...filters,group:draftGroup,city:draftCity.trim(),page:1});}}><div className="search-field blood-field"><label htmlFor="search-blood"><Droplet size={17}/>Blood group</label><GroupSelect value={draftGroup} onChange={setDraftGroup} id="search-blood" all/></div><div className="search-field location-field"><label htmlFor="search-city"><MapPin size={17}/>City or locality</label><input id="search-city" value={draftCity} onChange={e=>setDraftCity(e.target.value)} placeholder="e.g. Thane, Kalyan, Mumbai" maxLength={80}/></div><button className="btn primary search-button" type="submit"><Search size={19}/>Find donors</button></form>
 <div className="content-grid"><section className="donor-section" aria-label="Donor results"><div className="results-heading"><div><h2>{examples?"Example donor profiles":"Donor community"}<span className="count-pill">{loading&&!examples?"—":count}</span></h2><p>{examples?"Fictional examples for exploring the site.":"People ready to make a difference, one connection at a time."}</p></div><div className="availability-filter"><Switch id="available-filter" checked={filters.available} onCheckedChange={v=>setFilters({...filters,available:v,page:1})}/><label htmlFor="available-filter">Available only</label></div></div>
 {activeFilters&&<div className="filter-chips">{filters.group!=="all"&&<span>Blood group: {filters.group}</span>}{filters.city&&<span><MapPin size={13}/>{filters.city}</span>}<button onClick={resetFilters}>Clear filters<X size={13}/></button></div>}
 {examples&&<div className="example-notice"><Info size={17}/><span>These are sample profiles, not real donors. Contacting is disabled.</span><button onClick={()=>setExamples(false)}>View live donors<ArrowRight size={14}/></button></div>}
 <div aria-live="polite" aria-busy={loading&&!examples}>{loading&&!examples?<div className="donor-grid">{[1,2,3,4].map(i=><div className="donor-card" key={i}><Skeleton className="h-12 w-12 rounded-xl"/><Skeleton className="mt-5 h-5 w-3/5"/><Skeleton className="mt-3 h-4 w-4/5"/><Skeleton className="mt-8 h-10 w-full"/></div>)}</div>:searchError&&!examples?<Empty className="empty-state"><Info size={34}/><h3>We couldn’t load the donors</h3><p>{searchError}</p><button className="btn secondary" onClick={()=>setRefresh(v=>v+1)}>Try again</button></Empty>:displayed.length?<div className="donor-grid">{displayed.map((donor,i)=><article className="donor-card" key={donor.id}><div className="donor-card-top"><div className={`avatar avatar-${i%4}`}>{donor.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><span className="blood-badge"><Droplet size={15}/>{donor.bloodGroup}</span></div><h3>{donor.name}</h3><p className="donor-location"><MapPin size={15}/>{[donor.area,donor.city].filter(Boolean).join(", ")}</p><div className={`donor-status ${donor.available?"available":"paused"}`}><span/>{donor.available?"Available to be contacted":"Currently unavailable"}</div><div className="donor-card-bottom"><button className="btn secondary" disabled={!donor.available} onClick={()=>{setContactPhone("");setContactError("");setContactDonor(donor);}}><Phone size={16}/>{donor.sample?"View example":"Contact donor"}<ArrowUpRight size={16}/></button>{donor.sample?<small>Example profile</small>:<small><LockKeyhole size={11}/>Contact details require sign-in</small>}</div></article>)}</div>:<Empty className="empty-state"><div className="empty-icon"><HeartHandshake size={37} strokeWidth={1.3}/></div><h3>{activeFilters||(result.stats.registered>0&&filters.available)?"No donors found for this selection":"Every community starts with one person."}</h3><p>{activeFilters||(result.stats.registered>0&&filters.available)?"Try another location or blood group, or include donors whose availability is paused.":"Be the first to join BloodBridge. Your profile could be someone’s next connection."}</p>{activeFilters?<button className="btn secondary" onClick={resetFilters}><SlidersHorizontal size={16}/>Reset search</button>:<button className="btn primary" onClick={register}><Heart size={16}/>Join as a donor</button>}{!examples&&<button className="sample-link" onClick={()=>{resetFilters();setExamples(true);}}>Explore with sample profiles<ArrowRight size={14}/></button>}</Empty>}</div>
 {!examples&&result.pages>1&&<Pagination className="pagination"><button className="btn secondary" disabled={filters.page<=1||loading} onClick={()=>setFilters({...filters,page:filters.page-1})}><ChevronLeft size={16}/>Previous</button><span>Page {result.page} of {result.pages}</span><button className="btn secondary" disabled={filters.page>=result.pages||loading} onClick={()=>setFilters({...filters,page:filters.page+1})}>Next<ChevronRight size={16}/></button></Pagination>}<p className="results-footnote"><ShieldCheck size={15}/>Donors choose when they’re available. Confirm details directly before making plans.</p></section>
 <aside className="right-rail"><section className="donate-card"><div className="rail-icon"><HeartHandshake size={26} strokeWidth={1.4}/></div><span className="mini-label">BE THERE FOR SOMEONE</span><h2>A small act.<br/> A meaningful<br/> <em>difference.</em></h2><p>Join the donor community and let people nearby reach you when they need support.</p><button className="btn light" onClick={register}>Become a donor<ArrowRight size={17}/></button><div className="donate-caption"><Check size={13}/>Free to join. Always voluntary.</div></section><section className="community-card"><h3><Users size={17}/>Our growing community</h3><div><strong>{loading?"—":result.stats.registered}</strong><span>Registered donors</span></div><div><strong>{loading?"—":result.stats.available}</strong><span>Available now</span></div><div><strong>{loading?"—":result.stats.cities}</strong><span>Cities represented</span></div><p>Live counts from registered profiles.</p></section></aside></div>
 <section className="steps-strip"><div><span>01</span><div><h3>Find your blood group</h3><p>Choose a group and location.</p></div></div><div><span>02</span><div><h3>Connect with a donor</h3><p>Sign in to access contact details.</p></div></div><div><span>03</span><div><h3>Coordinate with the hospital</h3><p>Confirm the donation arrangements.</p></div></div></section></main>}
 {view==="profile"&&<main className="main-wrap profile-page"><div className="eyebrow"><span className="eyebrow-line"/>YOUR PLACE IN THE COMMUNITY</div><h1>My donor profile<span>.</span></h1><p className="page-lead">Keep your details current. Be available on your own terms.</p>{sessionError?<Empty className="empty-state"><h3>Your account couldn’t be loaded</h3><p>{sessionError}</p><button className="btn secondary" onClick={()=>void loadSession()}>Try again</button></Empty>:!session?<Skeleton className="h-64 w-full rounded-2xl"/>:!session.user?<Empty className="empty-state"><LockKeyhole size={32}/><h3>Your profile starts here</h3><p>Sign in to register as a donor or manage an existing profile.</p><button className="btn primary" onClick={()=>setAuthOpen(true)}>Sign in to continue<ArrowRight size={16}/></button></Empty>:<div className="profile-layout"><section className="profile-main">{session.profile?<><div className="profile-title"><div className="avatar avatar-0">{session.profile.name[0]}</div><div><h2>{session.profile.name}</h2><p>Voluntary blood donor</p></div><span className="blood-badge"><Droplet size={17}/>{session.profile.bloodGroup}</span></div><div className="availability-box"><div><h3>{session.profile.available?"You’re available to connect":"Your availability is paused"}</h3><p>{session.profile.available?"Signed-in blood seekers can view your contact number.":"Your contact number is hidden while you’re unavailable."}</p></div><Switch aria-label="Your donor availability" checked={session.profile.available} onCheckedChange={toggleAvailability} disabled={busy}/></div><dl className="profile-details"><div><dt>Blood group</dt><dd>{session.profile.bloodGroup}</dd></div><div><dt>City</dt><dd>{session.profile.city}</dd></div><div><dt>Locality</dt><dd>{session.profile.area||"Not added"}</dd></div><div><dt>Phone number</dt><dd>+91 {session.profile.phone}</dd></div></dl><button className="btn primary" onClick={register}>Edit donor profile<ArrowUpRight size={16}/></button></>:<Empty className="empty-state"><HeartHandshake size={37}/><h3>You haven’t joined as a donor yet</h3><p>Add your blood group, location and a contact number to get started.</p><button className="btn primary" onClick={register}>Create donor profile<ArrowRight size={16}/></button></Empty>}</section><aside className="profile-aside"><ShieldCheck size={25}/><h3>You’re in control.</h3><p>Your phone number is shared only with signed-in people while you’re available. Your account email stays private.</p><div className="account-detail"><span>Signed in as</span><strong>{session.user.email}</strong></div><button className="text-button" onClick={signOut}><LogOut size={16}/>Sign out</button>{session.profile&&<button className="delete-link" onClick={()=>setDeleteOpen(true)}>Delete donor profile</button>}</aside></div>}</main>}
 {view==="about"&&<main className="main-wrap about-page"><div className="eyebrow"><span className="eyebrow-line"/>A BRIDGE BETWEEN PEOPLE</div><h1>Help begins with<br/><span>a connection.</span></h1><p className="page-lead">BloodBridge brings voluntary donors and blood seekers together in one simple place.</p><div className="about-grid">{[{icon:Search,title:"Find a donor",text:"Choose the exact blood group and enter a city or locality. Use the availability filter to see people who are open to being contacted."},{icon:LockKeyhole,title:"Connect securely",text:"Sign in to view an available donor’s phone number. Call directly to discuss the hospital, timing and donation arrangements."},{icon:HeartHandshake,title:"Join the community",text:"Create your donor profile and manage your availability. You can update or remove your information whenever you need to."}].map((s,i)=><section key={s.title}><div className="about-step"><s.icon size={25}/><span>0{i+1}</span></div><h2>{s.title}</h2><p>{s.text}</p></section>)}</div><div className="about-note"><ShieldCheck size={28}/><div><h2>A connection service, built around people.</h2><p>BloodBridge does not collect, store, sell or supply blood. Profiles and availability are self-reported. A licensed hospital or blood bank must assess donation eligibility and blood compatibility. For urgent needs, contact your treating hospital directly.</p></div></div><div className="about-actions"><button className="btn primary" onClick={()=>navigate("find")}>Find donors<ArrowRight size={16}/></button><button className="btn secondary" onClick={register}>Become a donor</button></div><div className="project-credit"><p>FSJP Mini Project · 2026–27</p><h3>K. C. College of Engineering & Management Studies & Research</h3><p>Shaikh Yaseen · Shreyansh Singh · Sparsh Patel · Soham Kanase</p><p>Project guide: Dr. Nita Patil</p></div></main>}
 <footer className="site-footer"><div><a className="footer-brand" href="#find"><Droplet size={18} fill="currentColor"/>BloodBridge</a><span>Connecting people. Inspiring care.</span></div><p>For urgent blood requirements, contact your treating hospital or blood bank directly.</p><small>BloodBridge · FSJP Mini Project 2026–27</small></footer>
 <Dialog open={registerOpen} onOpenChange={setRegisterOpen}><DialogContent className="bb-dialog"><DialogHeader><div className="dialog-icon"><HeartHandshake size={25}/></div><DialogTitle>{session?.profile?"Edit your donor profile":"Be someone’s next connection"}</DialogTitle><DialogDescription>{session?.profile?"Update your details and availability.":"A few details are all it takes to join the donor community."}</DialogDescription></DialogHeader><ProfileForm key={session?.profile?.updatedAt||"new"} initial={session?.profile||null} userName={session?.user?.name||""} onSave={saveProfile}/></DialogContent></Dialog>
 <Dialog open={authOpen} onOpenChange={setAuthOpen}><DialogContent className="bb-dialog auth-dialog"><DialogHeader><div className="dialog-icon"><LockKeyhole size={24}/></div><DialogTitle>Welcome to BloodBridge</DialogTitle><DialogDescription>Sign in to contact donors or manage your own donor profile.</DialogDescription></DialogHeader>{session?.mode==="java"?<AuthForm api={api} onSuccess={async()=>{await loadSession();setAuthOpen(false);toast.success("You’re signed in.");}}/>:session?<><a className="btn primary" href={session.signInUrl||"/signin-with-chatgpt?return_to=/%23profile"} target="_top">Continue with ChatGPT<ArrowRight size={17}/></a><p className="dialog-help"><ShieldCheck size={16}/>Your email won’t appear in the donor directory.</p></>:sessionError?<div className="form-error" role="alert">{sessionError}<button className="sample-link" onClick={()=>void loadSession()}>Try again</button></div>:<p>Loading sign-in…</p>}</DialogContent></Dialog>
 <Dialog open={!!contactDonor} onOpenChange={open=>{if(!open)setContactDonor(null);}}><DialogContent className="bb-dialog"><DialogHeader><div className="dialog-icon"><Phone size={23}/></div><DialogTitle>{contactDonor?.sample?"This is an example profile":`Connect with ${contactDonor?.name}`}</DialogTitle><DialogDescription>{contactDonor?.sample?"Sample profiles help you explore the directory. They are fictional and cannot be contacted.":`${contactDonor?.bloodGroup} blood group · ${contactDonor?.city}`}</DialogDescription></DialogHeader>{contactDonor?.sample?<button className="btn primary" onClick={()=>{setContactDonor(null);setExamples(false);}}>View live donors<ArrowRight size={16}/></button>:!session?.user?<><p className="dialog-help">Sign in to view this donor’s contact details.</p><button className="btn primary" onClick={()=>{setContactDonor(null);setAuthOpen(true);}}>Sign in to continue<LockKeyhole size={16}/></button></>:contactError?<p className="form-error" role="alert">{contactError}</p>:contactPhone?<><div className="phone-display">+91 {contactPhone.slice(0,5)} {contactPhone.slice(5)}</div><a className="btn primary" href={`tel:+91${contactPhone}`}><Phone size={17}/>Call donor</a><p className="dialog-help">Introduce yourself, explain the requirement, and confirm arrangements with the treating hospital. Please respect the donor’s decision and time.</p></>:<p className="loading-inline"><Loader2 className="spin" size={18}/>Loading contact details…</p>}</DialogContent></Dialog>
 <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete your donor profile?</AlertDialogTitle><AlertDialogDescription>This removes your donor details and phone number from BloodBridge. You can create a new profile later. Your sign-in account will remain.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep my profile</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void deleteProfile();}}>{busy?"Deleting…":"Delete profile"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function ProfileForm({initial,userName,onSave}:{initial:Session["profile"];userName:string;onSave:(v:ProfileInput)=>Promise<void>}){
 const {register,handleSubmit,setValue,watch,formState:{errors,isSubmitting}}=useForm<ProfileInput>({resolver:zodResolver(profileSchema),defaultValues:{name:initial?.name||(userName.includes("@")?"":userName),bloodGroup:initial?.bloodGroup as ProfileInput["bloodGroup"]||undefined,city:initial?.city||"",area:initial?.area||"",phone:initial?.phone||"",available:initial?.available??true,consent:initial?.consent as true||undefined}});
 const [error,setError]=useState("");
 return <form className="profile-form" onSubmit={handleSubmit(async values=>{setError("");try{await onSave(values);}catch(err){setError((err as Error).message);}})}><div className="form-field"><label htmlFor="donor-name">Full name</label><input id="donor-name" autoComplete="name" placeholder="Your full name" {...register("name")} aria-invalid={!!errors.name}/>{errors.name&&<small className="field-error">{errors.name.message}</small>}</div><div className="form-row"><div className="form-field"><label htmlFor="donor-group">Blood group</label><GroupSelect id="donor-group" value={watch("bloodGroup")||""} onChange={v=>setValue("bloodGroup",v as ProfileInput["bloodGroup"],{shouldValidate:true})}/>{errors.bloodGroup&&<small className="field-error">Select your blood group.</small>}</div><div className="form-field"><label htmlFor="donor-city">City</label><input id="donor-city" placeholder="e.g. Thane" autoComplete="address-level2" {...register("city")} aria-invalid={!!errors.city}/>{errors.city&&<small className="field-error">{errors.city.message}</small>}</div></div><div className="form-field"><label htmlFor="donor-area">Locality <span>(optional)</span></label><input id="donor-area" placeholder="e.g. Kopri" {...register("area")}/>{errors.area&&<small className="field-error">{errors.area.message}</small>}</div><div className="form-field"><label htmlFor="donor-phone">Mobile number</label><div className="phone-input"><span>+91</span><input id="donor-phone" type="tel" autoComplete="tel-national" inputMode="tel" placeholder="10-digit mobile number" {...register("phone")} aria-invalid={!!errors.phone}/></div>{errors.phone&&<small className="field-error">{errors.phone.message}</small>}</div><div className="form-availability"><div><label htmlFor="donor-available">Available to be contacted</label><p>You can pause this at any time.</p></div><Switch id="donor-available" checked={watch("available")} onCheckedChange={v=>setValue("available",v)}/></div><div className="consent-row"><Checkbox id="donor-consent" checked={watch("consent")===true} onCheckedChange={v=>setValue("consent",(v===true) as true,{shouldValidate:true})}/><label htmlFor="donor-consent">I agree to list my name, blood group and location, and share my phone number with signed-in blood seekers while I’m available. Donation is voluntary and subject to the hospital’s assessment.</label></div>{errors.consent&&<small className="field-error">Please agree before saving your profile.</small>}{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="btn primary" disabled={isSubmitting}>{isSubmitting?<><Loader2 className="spin" size={17}/>Saving profile…</>:<>{initial?"Save changes":"Create donor profile"}<ArrowRight size={17}/></>}</button></form>;
}
function AuthForm({api,onSuccess}:{api:(p:string,o?:RequestInit)=>Promise<any>;onSuccess:()=>Promise<void>}){
 const [signup,setSignup]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 return <form className="profile-form" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError("");try{await api(signup?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(data))});await onSuccess();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{signup&&<div className="form-field"><label htmlFor="auth-name">Full name</label><input id="auth-name" name="name" required minLength={2} maxLength={80} autoComplete="name"/></div>}<div className="form-field"><label htmlFor="auth-email">Email address</label><input id="auth-email" type="email" name="email" required maxLength={180} autoComplete="email"/></div><div className="form-field"><label htmlFor="auth-password">Password</label><input id="auth-password" type="password" name="password" minLength={signup?10:1} maxLength={72} required autoComplete={signup?"new-password":"current-password"}/>{signup&&<small>Use at least 10 characters.</small>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy?"Please wait…":signup?"Create account":"Sign in"}<ArrowRight size={17}/></button><button type="button" className="sample-link" onClick={()=>{setSignup(v=>!v);setError("");}}>{signup?"Already have an account? Sign in":"New to BloodBridge? Create an account"}</button></form>;
}
