"use client";
import {ArrowRight,Droplet,Heart,HeartHandshake,HeartPulse,ShieldCheck,Award,Search,Users} from 'lucide-react';
import {ScrollReveal} from './scroll-reveal';
export function PrototypeHome({navigate,register}:{navigate:(v:string)=>void;register:()=>void}){
 return <main className="prototype-home">
 <section className="prototype-hero"><div className="hero-inner"><div className="hero-copy"><p className="hero-kicker">A CONNECTION THAT CAN SAVE A LIFE</p><h1>Donate blood.<br/>Be someone’s<br/><em>reason to hope.</em></h1><p>BloodBridge connects voluntary donors with people who need them. Find help nearby, or become that helping hand.</p><div className="hero-buttons"><button className="btn primary" onClick={()=>navigate('find')}><Search size={18}/>Find blood donors</button><button className="btn light" onClick={register}>Become a donor<ArrowRight size={17}/></button></div></div><div className="hero-mark" aria-hidden="true"><HeartPulse strokeWidth={1.15}/><span>BLOODBRIDGE</span></div></div></section>
 <section className="home-benefits main-wrap"><ScrollReveal><div className="section-intro"><span className="eyebrow">WHY YOUR DONATION MATTERS</span><h2>A little of you. A lot of hope.</h2></div><div className="benefit-grid">{[{icon:Droplet,title:'Support a life',text:'Help a patient connect with a willing donor.'},{icon:HeartHandshake,title:'Help your community',text:'Be there for people in your city.'},{icon:ShieldCheck,title:'Stay in control',text:'Choose your availability and protect your contact details.'},{icon:Heart,title:'Make it meaningful',text:'Build a verified history of voluntary donations.'}].map(item=><article key={item.title}><item.icon size={29} strokeWidth={1.7}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></ScrollReveal>
 <ScrollReveal className="home-recognition"><div><span className="eyebrow">YOUR KINDNESS, RECOGNISED</span><h2>Every receiver-confirmed donation<br/>adds to your story.</h2><p>Earn 500 recognition points for each receiver-confirmed donation. Reach 10 receiver-confirmed donations to receive your Saviour badge.</p><button className="btn primary" onClick={()=>navigate('rewards')}>Explore rewards<ArrowRight size={17}/></button></div><div className="milestone-preview"><Award size={46} strokeWidth={1.25}/><span>THE SAVIOUR MILESTONE</span><strong>10 donations.</strong><p>A lasting commitment to helping others.</p><div className="mini-milestones">{Array.from({length:10},(_,i)=><span key={i}><Droplet size={14}/></span>)}</div></div></ScrollReveal>
 <ScrollReveal className="home-how"><div className="section-intro"><span className="eyebrow">SIMPLE STEPS. REAL CONNECTIONS.</span><h2>How BloodBridge works</h2></div><div className="home-steps">{[{title:'Join the community',text:'Enter your email without an OTP, then save your private profile.',icon:Users},{title:'Find or offer support',text:'Search by blood group, state and city. Both people approve before contact is shared.',icon:Search},{title:'Record your contribution',text:'The receiver confirms blood received. The donor earns 500 points for that donation.',icon:Award}].map((item,i)=><article key={item.title}><span className="step-number">0{i+1}</span><item.icon size={24}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></ScrollReveal>
 <ScrollReveal className="home-cta"><HeartHandshake size={35}/><div><h2>Be the bridge someone needs.</h2><p>Your next connection could make a difference.</p></div><button className="btn light" onClick={register}>Join as a donor<ArrowRight size={17}/></button></ScrollReveal>
 <p className="home-health-note">Donation eligibility and safe intervals are decided by the blood centre. Rewards do not determine when you should donate. For urgent requirements, contact your treating hospital directly.</p>
 </section></main>;
}
