"use client";
import {useState} from 'react';
import {ArrowRight,Mail,ShieldCheck,Loader2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import type {ApiClient} from '@/lib/contracts';
export function SocialLogin({api,ready,onSuccess}:{api:ApiClient;ready:boolean;onSuccess:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>,admin:boolean){e.preventDefault();setBusy(true);setError('');try{await api(admin?'/api/auth/admin':'/api/auth/email',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await onSuccess();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Tabs defaultValue="member" className="login-tabs" onValueChange={()=>setError('')}><TabsList><TabsTrigger value="member">Member sign in</TabsTrigger><TabsTrigger value="admin">Admin portal</TabsTrigger></TabsList>
 <TabsContent value="member"><form className="profile-form" onSubmit={e=>void submit(e,false)}><div className="form-field"><label htmlFor="login-email">Email address</label><input id="login-email" name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={180}/></div><p className="dialog-help">No OTP or password. Your private profile stays linked to this browser. Entering the same email on another device creates a separate profile; it does not unlock existing records.</p><button className="btn primary" disabled={busy||!ready}>{busy?<Loader2 className="spin" size={17}/>:<Mail size={17}/>}Continue with email<ArrowRight size={16}/></button><small className="dialog-help">Use your personal device. Email ownership is not verified.</small></form></TabsContent>
 <TabsContent value="admin"><form className="profile-form" onSubmit={e=>void submit(e,true)}><div className="form-field"><label htmlFor="admin-username">Admin ID</label><input id="admin-username" name="username" autoComplete="username" required maxLength={80}/></div><div className="form-field"><label htmlFor="admin-password">Password</label><input id="admin-password" name="password" type="password" autoComplete="current-password" required maxLength={72}/></div><p className="dialog-help"><ShieldCheck size={16}/>Private donor records and family coordination. Admin sessions expire automatically.</p><button className="btn primary" disabled={busy}>{busy?<Loader2 className="spin" size={17}/>:<ShieldCheck size={17}/>}Open admin portal</button></form></TabsContent>{error&&<p className="form-error" role="alert">{error}</p>}</Tabs>;
}
