spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bloodbridge?serverTimezone=UTC}
spring.datasource.username=${DB_USER:bloodbridge}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/mysql
