spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=0
spring.jpa.properties.hibernate.default_schema=bloodbridge
spring.flyway.enabled=true
spring.flyway.schemas=bloodbridge
spring.flyway.default-schema=bloodbridge
spring.flyway.locations=classpath:db/migration/postgres
