package com.bloodbridge;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.*;
import java.util.*;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import static com.bloodbridge.AccessService.fail;
@RestController @RequestMapping("/api/matches")
public class MatchingController {
 private final BloodMatchRepository matches;private final AccountRepository accounts;private final DonorRepository donors;private final DonationRecordRepository donations;private final AccessService access;private final RateLimiter limits;private final InboxService notifications;
 public MatchingController(BloodMatchRepository matches,AccountRepository accounts,DonorRepository donors,DonationRecordRepository donations,AccessService access,RateLimiter limits,InboxService notifications){this.matches=matches;this.accounts=accounts;this.donors=donors;this.donations=donations;this.access=access;this.limits=limits;this.notifications=notifications;}
 public record RequestInput(@NotBlank @Size(max=36) String donorId,@NotBlank @Size(min=2,max=80) String patientName,@NotBlank @Size(min=3,max=120) String hospital,@NotBlank String bloodGroup,@NotBlank @Size(min=2,max=80) String state,@NotBlank @Size(min=2,max=80) String city,@Size(max=500) String note,@NotNull @AssertTrue Boolean consent){}
 public record Decision(@NotNull Boolean approve){}
 public record Received(@NotNull @AssertTrue Boolean confirmed,@NotBlank @Pattern(regexp="[0-9]{4}-[0-9]{2}-[0-9]{2}") String donationDate){}
 private Map<String,Object> dto(BloodMatch m,String owner){Map<String,Object> v=new HashMap<>();v.put("id",m.id);v.put("role",m.donorId.equals(owner)?"donor":"receiver");v.put("patientName",m.patientName);v.put("hospital",m.hospital);v.put("bloodGroup",m.bloodGroup);v.put("state",m.state);v.put("city",m.city);v.put("note",m.note);v.put("donorApproved",m.donorApproved);v.put("receiverApproved",m.receiverApproved);v.put("status",m.status);v.put("receivedAt",m.receivedAt);v.put("createdAt",m.createdAt);return v;}
 @GetMapping public Map<String,Object> inbox(Authentication auth){Account a=access.account(auth);return Map.of("matches",matches.findTop100ByDonorIdOrReceiverIdOrderByCreatedAtDesc(a.id,a.id).stream().map(m->dto(m,a.id)).toList(),"bloodReceived",matches.countByReceiverIdAndStatus(a.id,"received"));}
 @PostMapping @ResponseStatus(org.springframework.http.HttpStatus.CREATED) @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public Map<String,Object> create(@Valid @RequestBody RequestInput b,Authentication auth){
  Account a=access.account(auth);accounts.lockById(a.id).orElseThrow();if(donors.findByAccountId(a.id).isEmpty())throw fail(409,"Save your profile and contact number before requesting blood.");
  Donor d=donors.findByIdAndAvailableTrueAndConsentTrue(b.donorId()).orElseThrow(()->fail(404,"This donor is no longer available."));if(d.account.getId().equals(a.id))throw fail(400,"You cannot request your own donation.");if(!DonorController.GROUPS.contains(b.bloodGroup())||!b.bloodGroup().equals(d.bloodGroup))throw fail(400,"Choose a donor with the requested blood group. The hospital must confirm compatibility.");
  if(matches.existsByDonorIdAndReceiverIdAndStatusIn(d.account.getId(),a.id,List.of("pending","accepted")))throw fail(409,"You already have an open request with this donor.");limits.check("matches:"+a.id,15,86400000);
  BloodMatch m=new BloodMatch();m.donorId=d.account.getId();m.receiverId=a.id;m.patientName=b.patientName().trim();m.hospital=b.hospital().trim();m.bloodGroup=b.bloodGroup();m.state=b.state().trim();m.city=b.city().trim();m.note=b.note()==null?"":b.note().trim();matches.saveAndFlush(m);notifications.match(m,"New blood request received");return dto(m,a.id);
 }
 @PatchMapping("/{id}/decision") @Transactional public Map<String,Object> decision(@PathVariable String id,@Valid @RequestBody Decision b,Authentication auth){Account a=access.account(auth);BloodMatch m=owned(id,a.id);if(!m.status.equals("pending"))throw fail(409,"This request has already moved to its next stage.");if(b.approve()&&(m.donorId.equals(a.id)?m.donorApproved:m.receiverApproved))return dto(m,a.id);if(!b.approve()){m.status="declined";}else{if(m.donorId.equals(a.id))m.donorApproved=true;else m.receiverApproved=true;if(m.donorApproved&&m.receiverApproved)m.status="accepted";}m.updatedAt=System.currentTimeMillis();matches.save(m);notifications.match(m,b.approve()?"Blood request approval updated":"Blood request declined");return dto(m,a.id);}
 @GetMapping("/{id}/contact") @Transactional(readOnly=true) public Map<String,Object> contact(@PathVariable String id,Authentication auth){Account a=access.account(auth);BloodMatch m=matches.findById(id).orElseThrow(()->fail(404,"Request not found."));participant(m,a.id);if(!m.donorApproved||!m.receiverApproved||!Set.of("accepted","received").contains(m.status))throw fail(403,"Both people must approve before contact details are shared.");String other=m.donorId.equals(a.id)?m.receiverId:m.donorId;Donor d=donors.findByAccountId(other).orElseThrow(()->fail(404,"The other person has removed their contact profile."));return Map.of("name",d.name,"phone",d.phone);}
 @PostMapping("/{id}/received") @Transactional public Map<String,Object> received(@PathVariable String id,@Valid @RequestBody Received b,Authentication auth){
  Account a=access.account(auth);BloodMatch m=owned(id,a.id);if(!m.receiverId.equals(a.id))throw fail(403,"Only the receiver can confirm blood received.");if(m.status.equals("received"))return Map.of("success",true,"alreadyRecorded",true);if(!m.status.equals("accepted")||!m.donorApproved||!m.receiverApproved)throw fail(409,"Both approvals are required before confirming receipt.");
  LocalDate date;try{date=LocalDate.parse(b.donationDate());}catch(Exception e){throw fail(400,"Enter a valid donation date.");}LocalDate today=LocalDate.now(ZoneOffset.UTC),created=Instant.ofEpochMilli(m.createdAt).atZone(ZoneOffset.UTC).toLocalDate();if(date.isAfter(today)||date.isBefore(created))throw fail(400,"The donation date must be between the request date and today.");
  accounts.lockById(m.donorId).orElseThrow();if(donations.existsByOwnerIdAndDonationDate(m.donorId,b.donationDate()))throw fail(409,"A donation is already recorded for this donor on that date. Ask the administrator to check the record.");
  DonationRecord d=new DonationRecord();d.ownerId=m.donorId;d.donationDate=b.donationDate();d.center=m.hospital;d.reference="MATCH-"+m.id;d.referenceKey=SupabaseAuthProvider.hash(d.reference);d.status="verified";d.reviewNote="Blood received confirmed by the receiver after both approvals.";d.reviewedBy=a.id;donations.saveAndFlush(d);m.status="received";m.receivedAt=System.currentTimeMillis();m.updatedAt=m.receivedAt;matches.saveAndFlush(m);notifications.match(m,"Blood received confirmed by the receiver");return Map.of("success",true,"pointsAdded",500,"status","received");
 }
 private BloodMatch owned(String id,String owner){BloodMatch m=matches.lockById(id).orElseThrow(()->fail(404,"Request not found."));participant(m,owner);return m;}
 private void participant(BloodMatch m,String owner){if(!m.donorId.equals(owner)&&!m.receiverId.equals(owner))throw fail(404,"Request not found.");}
}
