package com.bloodbridge;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.*;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.context.ApplicationEventPublisher;
import static com.bloodbridge.AccessService.fail;
@RestController @RequestMapping("/api")
public class RewardsController {
 private final DonationRecordRepository donations;private final FamilyRequestRepository families;private final AccountRepository accounts;private final DonorRepository donors;private final ProgramSettings program;private final AccessService access;private final EmailNoticeRepository notices;private final FamilyEmailService email;private final ApplicationEventPublisher events;private final InboxService inbox;
 public RewardsController(DonationRecordRepository donations,FamilyRequestRepository families,AccountRepository accounts,DonorRepository donors,ProgramSettings program,AccessService access,EmailNoticeRepository notices,FamilyEmailService email,ApplicationEventPublisher events,InboxService inbox){this.donations=donations;this.families=families;this.accounts=accounts;this.donors=donors;this.program=program;this.access=access;this.notices=notices;this.email=email;this.events=events;this.inbox=inbox;}
 public record FamilyInput(@NotBlank @Size(max=30) String relationship,@NotBlank @Size(min=2,max=80) String patientName,@NotBlank @Size(min=3,max=120) String hospital,@NotBlank @Size(min=2,max=80) String state,@NotBlank @Size(min=2,max=80) String city,@NotBlank String bloodGroup,@NotBlank @Size(max=25) String phone,@NotNull @AssertTrue Boolean consent){}
 public record ReviewInput(@NotBlank String status,@NotBlank @Size(min=5,max=500) String note){}
 private static Map<String,Object> donationDto(DonationRecord d){return Map.of("id",d.id,"donationDate",d.donationDate,"center",d.center,"reference",d.reference,"status",d.status,"reviewNote",d.reviewNote,"createdAt",d.createdAt);}
 private Map<String,Object> familyDto(FamilyRequest f){Map<String,Object> v=new HashMap<>();v.put("id",f.id);v.put("relationship",f.relationship);v.put("patientName",f.patientName);v.put("requesterName",f.requesterName);v.put("email",f.email);v.put("hospital",f.hospital);v.put("state",f.state);v.put("city",f.city);v.put("bloodGroup",f.bloodGroup);v.put("phone",f.phone);v.put("status",f.status);v.put("note",f.note);v.put("createdAt",f.createdAt);v.put("emailStatus",notices.findById(f.id).map(n->n.status).orElse("pending"));return v;}
 @GetMapping("/rewards") public Map<String,Object> rewards(Authentication auth){Account a=access.account(auth);long count=donations.countByOwnerIdAndStatus(a.id,"verified"),used=families.countByOwnerIdAndStatusNot(a.id,"cancelled");Map<String,Object> v=new HashMap<>();v.put("verifiedDonations",count);v.put("points",count*500);v.put("saviour",count>=10);v.put("donations",donations.findTop200ByOwnerIdOrderByDonationDateDescCreatedAtDesc(a.id).stream().map(RewardsController::donationDto).toList());v.put("requests",families.findTop50ByOwnerIdOrderByCreatedAtDesc(a.id).stream().map(this::familyDto).toList());v.put("familyUsesRemaining",Math.max(0,2-used));v.put("cashRedemptionEnabled",false);v.put("assistanceEnabled",program.assistanceEnabled);v.put("emailReady",email.configured());v.put("isAdmin",program.isAdmin(a));return v;}
 @PostMapping("/rewards/claims") public void cashClaim(){throw fail(409,"Cash redemption is not enabled. The conversion is a classroom demonstration only.");}
 @PostMapping("/donations") public void donate(){throw fail(409,"Donations are recorded only when the receiver confirms Blood received after both approvals. Open Requests to continue.");}
 @PatchMapping("/admin/donations/{id}") public void reviewDonation(@PathVariable String id,Authentication auth){access.admin(auth);throw fail(409,"Only the receiver can confirm a donation after both approvals.");}
 @PostMapping("/family") @ResponseStatus(org.springframework.http.HttpStatus.CREATED) @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public Map<String,Object> family(@Valid @RequestBody FamilyInput b,Authentication auth){
  Account a=access.account(auth);accounts.lockById(a.id).orElseThrow();if(donations.countByOwnerIdAndStatus(a.id,"verified")<10)throw fail(403,"The Saviour badge unlocks after 10 receiver-confirmed donations.");if(!program.assistanceEnabled)throw fail(503,"Family assistance is not active yet.");if(families.countByOwnerIdAndStatusNot(a.id,"cancelled")>=2)throw fail(409,"Both family-support uses are already reserved or completed.");
  if(!DonorController.GROUPS.contains(b.bloodGroup())||!Set.of("Parent","Spouse","Child","Sibling","Other family").contains(b.relationship()))throw fail(400,"Check the family relationship and blood group.");String phone=b.phone().replaceAll("[\\s()-]","").replaceFirst("^\\+91","");if(!phone.matches("[6-9][0-9]{9}"))throw fail(400,"Enter a valid contact mobile number.");
  FamilyRequest f=new FamilyRequest();f.ownerId=a.id;f.patientName=b.patientName().trim();f.requesterName=donors.findByAccountId(a.id).map(d->d.name).orElse(a.name);f.email=a.email==null?"":a.email;f.relationship=b.relationship();f.hospital=b.hospital().trim();f.state=b.state().trim();f.city=b.city().trim();f.bloodGroup=b.bloodGroup();f.phone=phone;families.saveAndFlush(f);inbox.family(f);
  EmailNotice n=new EmailNotice();n.id=f.id;n.subject="Saviour family request: "+f.bloodGroup+" | "+f.city;n.messageBody=String.join("\n","New BloodBridge Saviour family request","Request ID: "+f.id,"Saviour: "+f.requesterName,"Email (self-entered, unverified): "+f.email,"Patient: "+f.patientName,"Relationship: "+f.relationship,"Required blood group: "+f.bloodGroup,"Hospital: "+f.hospital,"State: "+f.state,"City: "+f.city,"Contact phone: +91 "+f.phone,"Request time (UTC): "+java.time.Instant.ofEpochMilli(f.createdAt),"Both lifetime family-support uses include open and completed requests. A cancelled request restores one use.","Open the administrator portal to coordinate. Blood availability requires hospital confirmation.");notices.saveAndFlush(n);events.publishEvent(new FamilyNoticeCreated(f.id));return Map.of("success",true,"id",f.id,"status","requested","message","Family request saved for coordination.");
 }
 @GetMapping("/admin/reviews") public Map<String,Object> reviews(Authentication auth){access.admin(auth);return Map.of("donations",List.of(),"requests",families.findTop100ByStatusInOrderByCreatedAtAsc(List.of("requested","in_progress","closed")).stream().map(this::familyDto).toList(),"emailReady",email.configured());}
 @PatchMapping("/admin/family/{id}") @Transactional public Map<String,Boolean> reviewFamily(@PathVariable String id,@Valid @RequestBody ReviewInput b,Authentication auth){access.admin(auth);if(!Set.of("in_progress","closed","cancelled").contains(b.status())||b.note().trim().length()<5)throw fail(400,"Add a valid status and update.");FamilyRequest f=families.findForReview(id).orElseThrow(()->fail(404,"Request not found."));if(Set.of("closed","cancelled").contains(f.status))throw fail(409,"This request is already closed.");f.status=b.status();f.note=b.note().trim();f.updatedAt=System.currentTimeMillis();families.save(f);inbox.family(f);return Map.of("success",true);}
 @PostMapping("/admin/family/{id}/email/retry") public Map<String,Boolean> retryEmail(@PathVariable String id,Authentication auth){access.admin(auth);if(!email.configured())throw fail(503,"Set the email provider key and a verified sender first.");email.retryNow(id);return Map.of("success",true);}
}
